-- 1. Table Tickets (Updated for Context)
create table if not exists public.helpdesk_tickets (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    user_name text,
    user_email text,
    subject text not null,
    status text default 'open',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FORCE ADD COLUMNS (Fix for existing table)
do $$ 
begin
    alter table public.helpdesk_tickets add column if not exists product_info jsonb;
    alter table public.helpdesk_tickets add column if not exists order_id text;
exception
    when others then null;
end $$;

-- 2. Table Messages
create table if not exists public.helpdesk_messages (
    id bigint generated by default as identity primary key,
    ticket_id bigint references public.helpdesk_tickets(id) on delete cascade not null,
    sender_id uuid references auth.users not null,
    sender_role text not null,
    message text not null,
    is_image boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. RLS (Drop first to avoid collision)
alter table public.helpdesk_tickets enable row level security;
alter table public.helpdesk_messages enable row level security;

drop policy if exists "Users manage own tickets" on public.helpdesk_tickets;
drop policy if exists "Admins view all tickets" on public.helpdesk_tickets;
drop policy if exists "Admins update tickets" on public.helpdesk_tickets;

create policy "Users manage own tickets" on public.helpdesk_tickets for all using (auth.uid() = user_id);
create policy "Admins view all tickets" on public.helpdesk_tickets for select using (exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'bos')));
create policy "Admins update tickets" on public.helpdesk_tickets for update using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

drop policy if exists "Users view messages of own tickets" on public.helpdesk_messages;
drop policy if exists "Users store messages" on public.helpdesk_messages;
drop policy if exists "Admins view all messages" on public.helpdesk_messages;
drop policy if exists "Admins send messages" on public.helpdesk_messages;

create policy "Users view messages of own tickets" on public.helpdesk_messages for select using (exists (select 1 from public.helpdesk_tickets where id = ticket_id and user_id = auth.uid()));
create policy "Users store messages" on public.helpdesk_messages for insert with check (exists (select 1 from public.helpdesk_tickets where id = ticket_id and user_id = auth.uid()));
create policy "Admins view all messages" on public.helpdesk_messages for select using (exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'bos')));
create policy "Admins send messages" on public.helpdesk_messages for insert with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- 4. Realtime (Safe Add)
begin;
  -- Try adding tickets table
  do $$ begin
    alter publication supabase_realtime add table public.helpdesk_tickets;
  exception when duplicate_object then null; end $$;
  
  -- Try adding messages table
  do $$ begin
    alter publication supabase_realtime add table public.helpdesk_messages;
  exception when duplicate_object then null; end $$;
commit;
